@startuml Use Case Diagram
:Tester: -left-> (Move to another Field)
:Tester: -left-> (Steal Equipment from paralyzed Virologist)
:Tester: -left-> (Steal Equipment from non-paralyzed Virologist)
:Tester: -up-> (Create ChoreaVirus)
:Tester: -up-> (Create MemoryLossVirus)
:Tester: -up-> (Create ParalyzingVirus)
:Tester: -up-> (Create Vaccine)
:Tester: -up-> (Collect Material with Sack)
:Tester: -up-> (Collect Material without Sack)
:Tester: -up-> (Scan new Genetic Code)
:Tester: -right-> (Scan already known Genetic Code)
:Tester: -right-> (Pick up Equipment when not full)
:Tester: -right-> (Pick up Equipment when full)
:Tester: -right-> (Drop Equipment)
:Tester: -down-> (Use MemoryLossVirus)
:Tester: -down-> (Use ChoreaVirus)
:Tester: -down-> (Use ChoreaVirus when protected by Vaccine)
:Tester: -down-> (Use ChoreaVirus when protected by WhiteCoat)
:Tester: -down-> (Use ChoreaVirus when reflected by Gloves)
:Tester: -down-> (Virologist moves with ChoreaVirus infection)
@enduml